### ISSUE TITLE
achievement folder & file occationally not added until pressing escape (doesnt save on load)

### ISSUE THREAD

**Issue by Specnr** [Mario0051/chunk-mod#3]
title says it all, also it doesnt save all chunks and write to logs every time, although sometimes it does

when it does:
![image](https://user-images.githubusercontent.com/74469583/132802245-87b39dd0-f4dd-4dac-b97a-1a52cc90bcc8.png)
when it doesnt: 
![image](https://user-images.githubusercontent.com/74469583/132802345-b5ca068e-91c7-44cb-8273-27d36145c9b1.png)
![image](https://user-images.githubusercontent.com/74469583/132801903-935aaaa8-7fdc-465e-8fdd-c28a544df2f9.png)

**Comment by Specnr** [comment]
im also using the lazy stronghold mod, but this issue doesnt happen if i dont use this mod

**Comment by Gregor0410** [comment]
injecting this.save(false,false,false) at the tail of MinecraftServer.prepareStartRegion() should fix this
